name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make application.yml
      run: |
        mkdir -p ./src/main/resources
        echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      shell: bash

    - name: Test with Gradle
      run: |
        cd ./demo
        ./gradlew test
        
    - name: Build with Gradle
      run: |
        cd ./demo
        ./gradlew build -x test
  
    - name: Make zip file
      run: |
        cd ./demo
        mkdir deploy
        cd ..
        cp ./appspec.yml ./demo/deploy
        cp ./Dockerfile ./demo/deploy
        cp ./*.sh ./demo/deploy
        cd ./demo
        cp ./build/libs/*.jar ./demo/deploy
        zip -r -qq -j ./spring-build.zip ./demo/deploy
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Upload to S3
      run: |
        cd ./demo
        aws s3 cp \
           --region ap-northeast-2 \
          ./spring-build.zip s3://travel-spring

    - name: Code Deploy
      run: aws deploy create-deployment --application-name spring-deploy
         --deployment-config-name CodeDeployDefault.OneAtATime
         --deployment-group-name spring-deploy-group
         --s3-location bucket=travel-spring,bundleType=zip,key=spring-build.zip
